### ISSUE TITLE
restapi spring boot starter

### ISSUE THREAD

**Issue by nuck-740** [osteinhauer/camunda-spring-boot-starter-examples#1]
I have followed this example  I am not able to deploy the process using http://localhost:8080/rest/engine/deployment/create with request body as
{
"deployment-name":"example"
} and Content-Type as application/json
. How do I deploy and start a process?

**Comment by nuck-740** [comment]
``

**Comment by osteinhauer** [comment]
See [Rest Api Reference](https://docs.camunda.org/manual/7.6/reference/rest/)
